### ISSUE TITLE
Inspection mode opens every time Alt+Tab is pressed in Firefox and does not close

### ISSUE THREAD

**Issue by rualark** [discoveryjs/discovery#77] opened 2020-12-07 09:48 UTC
Why do users need inspection mode? It seems to be needed only for development?
As Alt+Tab is pressed all the time, it now makes plugin difficult to use: every time before working with plugin (and even before seeing anything), you need to press Esc or Alt. And sometimes this does not work for some reason due to some focus issues - so after trying to press Esc or Alt several times, you realise that you need first to click at some whitespace in plugin - so you look for whitespace, click there and now you can press Esc or Alt to disable inspection mode. And this happens every time after you swith with Alt-Tab :)

**Comment by lahmatiy** [comment] 2020-12-07 10:20
Yes, that's doesn't work as intended and may be annoying. Sorry about that.
Will be fixed in next release (optimistic today or tomorrow).

**Closed** 2020-12-07 13:53 UTC
